-- ================================================
-- ESQUEMA INICIAL
-- Debe coincidir con las entidades JPA (ddl-auto: validate)
-- ================================================
CREATE TABLE region (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero  VARCHAR(5)   NOT NULL,
    nombre  VARCHAR(100) NOT NULL,
    capital VARCHAR(100) NOT NULL
);

CREATE TABLE provincia (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(100) NOT NULL,
    capital   VARCHAR(100) NOT NULL,
    region_id BIGINT       NOT NULL REFERENCES region (id)
);

CREATE TABLE comuna (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    codigo_cut   VARCHAR(10)  NOT NULL UNIQUE,
    provincia_id BIGINT       NOT NULL REFERENCES provincia (id)
);

CREATE INDEX idx_provincia_region_id ON provincia (region_id);
CREATE INDEX idx_comuna_provincia_id ON comuna (provincia_id);
